



variable "owner_name" {
  type        = string
  description = "Owner of the new image generated by Packer"
}

variable "purpose" {
  type    = string
  default = "custom"
}

variable "az_client_id" {
  type = string
  default = env("AZ_CLIENT_ID")
}

variable "az_client_secret" {
  type = string
  default = env("AZ_CLIENT_SECRET")
}

variable "az_subscription_id" {
  type = string
  default = env("AZ_SUBSCRIPTION_ID")
}

variable "az_resource_group" {
  type = string
}