variable "region" {
  type    = string
}

variable "instance_type" {
  type    = string
  default = "t2.micro"
}

variable "volume_size" {
  type    = string
  default = "20"
}

variable "baseos_name" {
  type    = string
}

variable "baseos_aminame" {
  type    = string
}

variable "baseos_sshuser" {
  type    = string
}

variable "baseos_version" {
  type    = string
}

variable "baseos_owner" {
  type    = string
}

variable "baseos_arch" {
  type    = string
}

variable "owner_name" {
  type        = string
  description = "Owner of the new image generated by Packer"
}

variable "purpose" {
  type    = string
  default = "custom"
}