

---

name: Packer Build/Patch All (Multi Environment)

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer-ubuntu-multienv

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Distribute Vars 
        run: cd multi-env/ && echo centos/ ubuntu/ | xargs -n 1 cp vars.pkrvars.hcl

      - name: Packer Init - Ubuntu
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: .
          working_directory: multi-env/ubuntu

      - name: Packer Init - Ubuntu
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: .
          working_directory: multi-env/centos

      # validate templates
      - name: Validate Ubuntu Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: "-syntax-only -var-file=vars.pkrvars.hcl"
          target: .
          working_directory: multi-env/ubuntu

      - name: Validate CentOS Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: "-syntax-only -var-file=vars.pkrvars.hcl"
          target: .
          working_directory: multi-env/centos

      # build artifacts
      - name: Build/Patch Ubuntu
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var \"az_client_id={{ env `AZ_CLIENT_ID` }}\" -var \"az_client_secret={{ env `AZ_CLIENT_SECRET` }}\" -var \"az_subscription_id={{ env `AZ_SUBSCRIPTION_ID` }}\""
          target: .
          working_directory: multi-env/ubuntu
        env:
          PACKER_LOG: 1
          AZ_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
          AZ_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
          AZ_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}

      - name: Build/Patch CentOS
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var-file=vars.pkrvars.hcl"
          target: .
          working_directory: multi-env/centos
        env:
          PACKER_LOG: 1
          ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}